services:
  # Service for Notification service
  notification-service:
    build: ./notification-service
    image: notification-service
    container_name: notification-service
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes:
      - ./notification-service:/app
      - /app/node_modules
    depends_on:
      - dynamodb # Ensure DynamoDB Local is started before the app
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - NODE_ENV=development
    command: npm run dev

  # Service for DynamoDB Local
  dynamodb:
    image: amazon/dynamodb-local # Use the official DynamoDB Local image
    container_name: dynamodb-local
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
      - /home/dynamodblocal/data
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data" ]

  # SQL Database for Logging Service
  postgres:
    image: postgres:16-alpine
    container_name: logging-db-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=logging_user
      - POSTGRES_PASSWORD=logging_pass
      - POSTGRES_DB=logging_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
